version: 2.1

executors:
  default-executor:
    docker:
      - image: cimg/base:current

jobs:
  build:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: "Compilar el proyecto"
          command: "echo Compilando el proyecto..."
      - run:
          name: "Instalar dependencias"
          command: "echo Instalando dependencias..."
  
  test-unit:
    executor: default-executor
    parallelism: 2 # Ejecutar el job en paralelo
    steps:
      - checkout
      - run:
          name: "Ejecutar pruebas unitarias"
          command: "echo Ejecutando pruebas unitarias..."

  test-integration:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: "Ejecutar pruebas de integración"
          command: "echo Ejecutando pruebas de integración..."

  lint:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: "Ejecutar análisis de código (lint)"
          command: "echo Ejecutando análisis de código..."

  notify:
    executor: default-executor
    steps:
      - run:
          name: "Enviar notificación por correo"
          command: "echo Enviando notificación por correo electrónico..."

workflows:
  pruebas-paralelas:
    jobs:
      - build
      - test-unit:
          requires:
            - build
      - test-integration:
          requires:
            - build
      - lint:
          requires:
            - build

  flujo-notificaciones:
    jobs:
      - build

notify:
  emails:
    recipients:
      - "mateo.velasquez@udla.edu.ec"
    on_success: change # Enviar notificación solo si hay cambios en el estado de éxito
    on_fail: always # Enviar notificación siempre en caso de fallo
